#ifndef KEYROXTKLMODES_HPP
#define KEYROXTKLMODES_HPP

enum class KeyroxModes
{
  WAVE_MODE_VALUE = 0x00,
  CONST_MODE_VALUE = 0x01,
  BREATHE_MODE_VALUE = 0x02,
  HEARTRATE_MODE_VALUE = 0x03,
  POINT_MODE_VALUE = 0x04,
  WINNOWER_MODE_VALUE = 0x05,
  STARS_MODE_VALUE = 0x06,
  SPECTRUM_MODE_VALUE = 0x07,
  PLUMFLOWER_MODE_VALUE = 0x08,
  SHOOT_MODE_VALUE = 0x09,
  AMBILIGHT_ROTATE_MODE_VALUE = 0x0A,
  RIPPLE_MODE_VALUE = 0x0B,
  CUSTOM_MODE_VALUE = 0x0C
};

#endif
